version: '3.8'
services:
  mysql8:
    platform: linux/amd64
    image: mysql:8.0.34
    command:
      - --sql-mode=
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql8-data:/var/lib/mysql
      - ./docker/mysql8/conf.d:/etc/mysql/conf.d

  mysql57:
    platform: linux/amd64
    image: mysql:5.7
    command:
      - --sql-mode=
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql57-data:/var/lib/mysql
      - ./docker/mysql57/conf.d:/etc/mysql/conf.d

volumes:
  mysql8-data:
  mysql57-data:
