openapi: 3.0.0
info:
  title: Bookstore API
  version: 1.0.0
  description: API to retrieve book information
servers:
  - url: http://localhost:3000

paths:
  /books:
    get:
      summary: List all books
      operationId: listBooks
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/{bookId}:
    get:
      summary: Get a book by ID
      operationId: getBookById
      parameters:
        - name: bookId
          in: path
          required: true
          description: Unique identifier of the book
          schema:
            type: string
      responses:
        '200':
          description: Details of the book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: string
          description: Unique identifier of the book
        title:
          type: string
          description: Title of the book
        author:
          type: string
          description: Author of the book
        isbn:
          type: string
          description: ISBN of the book
        publishedDate:
          type: string
          format: date
          description: Date when the book was published

