
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc: v1.26.0
# source: Models.pm

package ;
use strict;
use warnings;

use Types::Standard -types;





use kote Authors => Dict[
  id => Str,
  name => Str,
  bio => Str,
];




1;
